### ISSUE TITLE
Support new stage RC 1 for 4.5.3 in wazuh-docker repository

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-docker#1006]
## Description

This issue attempts to support a new stage RC 1 for 4.5.3 in the wazuh-docker repository.

## Tasks

- [ ] ~~Ensure changelog is updated for 4.5.3 (if applicable).~~
- [ ] ~~Bump revision for branch 4.5.3 on wazuh-docker repository.~~
- [x] Create tag v4.5.3-rc1 from branch 4.5.3 on wazuh-docker repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-docker/releases/tag/v4.5.3-rc1.
