### ISSUE TITLE
Support new stage Beta 1 for 4.6.0 in wazuh-docker repository

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-docker#1012]
## Description

This issue attempts to support a new stage Beta 1 for 4.6.0 in the wazuh-docker repository.

## Tasks

- [ ] ~~Ensure changelog is updated for 4.6.0 (if applicable)~~ (up to date)
- [ ] ~~Bump revision for branch 4.6.0 on wazuh-docker repository.~~ (up to date)
- [x] Bump revision to `40601`.
- [x] Create tag v4.6.0-beta1 from branch 4.6.0 on wazuh-docker repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-docker/releases/tag/v4.6.0-beta1.
