### ISSUE TITLE
Support new stage RC 2 for 4.5.3 in wazuh-docker repository

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-docker#1020]
## Description

This issue attempts to support a new stage RC 2 for 4.5.3 in the wazuh-docker repository.

## Tasks

- [x] Ensure changelog is updated for 4.5.3 (if applicable).
- [x] Bump revision for branch 4.5.3 on wazuh-docker repository. https://github.com/wazuh/wazuh-docker/pull/1021
- [x] Create tag v4.5.3-rc2 from branch 4.5.3 on wazuh-docker repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-docker/releases/tag/v4.5.3-rc2.
