### ISSUE TITLE
Support new stage RC 1 for 4.6.0 in wazuh-docker repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-docker#1032]
## Description

This issue attempts to support a new stage RC 1 for 4.6.0 in the wazuh-docker repository.

## Tasks

- [ ] Ensure changelog is updated for 4.6.0 (if applicable).
- [ ] Bump revision for branch 4.6.0 on wazuh-docker repository.
- [ ] Create tag v4.6.0-rc1 from branch 4.6.0 on wazuh-docker repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-docker/releases/tag/v4.6.0-rc1.
