### ISSUE TITLE
Post release tasks for 4.5.3

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-docker#1046]
## Description
This issue attempts to track steps necessary to complete post-release maintenance tasks for 4.5.3.
The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.5.3-into-4.6.0`.

## Tasks

- [ ] Merge branch `4.5.3` into branch `4.6.0`.
- [ ] Merge branch `4.6.0` into branch `4.7.0`.
- [ ] Merge branch `4.7.0` into branch `4.7.1`.
- [ ] Merge branch `4.7.1` into branch `master`.
- [ ] Publish GitHub release as latest.
- [ ] Delete all stage pre-releases for 4.5.3 (https://github.com/wazuh/wazuh-docker/releases).
- [ ] Delete all stage tags for v4.5.3. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.5.3-rc1, 4.5.3-alpha1, etc.
- [ ] Delete branch `4.5.3`.
- [ ] Update [Docker hub](https://hub.docker.com/u/wazuh) readme compatibility matrix to include 4.5.3 for manager, dashboard, and indexer.
- [ ] Delete all stage [Docker hub images](https://hub.docker.com/u/wazuh) for v4.5.3. **BE CAREFUL NOT TO DELETE DEFINITIVE DOCKER IMAGES**. Example: v4.5.3-rc1, 4.5.3-alpha1, etc.
