### ISSUE TITLE
Support new stage Alpha 1 for 4.5.4 in wazuh-docker repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-docker#1060]
## Description

This issue attempts to support a new stage Alpha 1 for 4.5.4 in the wazuh-docker repository.

## Tasks

- [x] Ensure changelog is updated for 4.5.4 (if applicable).
- [x] Bump revision for branch 4.5.4 on wazuh-docker repository. https://github.com/wazuh/wazuh-docker/pull/1061
- [x] Create tag v4.5.4-alpha1 from branch 4.5.4 on wazuh-docker repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-docker/releases/tag/v4.5.4-alpha1.

**Comment by vcerenu** [comment]
LGTM
