### ISSUE TITLE
Post release tasks for 4.6.0

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-docker#1089]
## Description
This issue attempts to track the steps necessary to complete post-release maintenance tasks for 4.6.0.
The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.6.0-into-4.7.0`.

## Tasks

- [ ] ~~Merge branch `4.6.0` into branch `4.7.0`.~~ Up to date.
- [ ] ~~Merge branch `4.7.0` into branch `4.7.1`.~~ Up to date.
- [x] Merge branch `4.7.1` into branch `4.8.0`.https://github.com/wazuh/wazuh-docker/pull/1092
- [ ] Merge branch `4.8.0` into branch `master`. https://github.com/wazuh/wazuh-docker/pull/1093
- [x] Publish GitHub release as latest.
- [x] Delete all stage pre-releases for 4.6.0 (https://github.com/wazuh/wazuh-docker/releases).
- [x] Delete all stage tags for v4.6.0. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.6.0-rc1, 4.6.0-alpha1, etc.
- [x] Delete branch `4.6.0`.
- [x] Update [Docker hub](https://hub.docker.com/u/wazuh) readme compatibility matrix to include 4.6.0 for manager, dashboard, and indexer.
- [x] Delete all stage [Docker hub images](https://hub.docker.com/u/wazuh) for v4.6.0. **BE CAREFUL NOT TO DELETE DEFINITIVE DOCKER IMAGES**. Example: v4.6.0-rc1, 4.6.0-alpha1, etc.
