### ISSUE TITLE
Support new stage RC 1 for 4.7.1 in wazuh-docker repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-docker#1134]
## Description

This issue attempts to support a new stage RC 1 for 4.7.1 in the wazuh-docker repository.

## Tasks

- [x] Ensure changelog is updated for 4.7.1 (if applicable).
- [x] Bump revision for branch 4.7.1 on wazuh-docker repository. https://github.com/wazuh/wazuh-docker/pull/1135
- [x] Create tag v4.7.1-rc1 from branch 4.7.1 on wazuh-docker repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-docker/releases/tag/v4.7.1-rc1.
