### ISSUE TITLE
Support new stage Beta 2 for 4.8.0 in wazuh-docker repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-docker#1228]
## Description

This issue attempts to support a new stage Beta 2 for 4.8.0 in the wazuh-docker repository.

## Tasks

- [ ] Ensure changelog is updated for 4.8.0 (if applicable).
- [ ] Bump revision for branch 4.8.0 on wazuh-docker repository.
- [ ] Create tag v4.8.0-beta2 from branch 4.8.0 on wazuh-docker repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-docker/releases/tag/v4.8.0-beta2.
