### ISSUE TITLE
Support new stage RC 1 for 4.7.4 in wazuh-docker repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-docker#1308]
## Description

This issue attempts to support a new stage RC 1 for 4.7.4 in the wazuh-docker repository.

## Tasks

- [x] Ensure changelog is updated for 4.7.4 (if applicable).
- [x] Bump revision for branch 4.7.4 on wazuh-docker repository.
- [x] Change docker image tag in docker-compose to tag v4.7.4-rc1 in branch 4.7.4
- [x] Create tag v4.7.4-rc1 from branch 4.7.4 on wazuh-docker repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-docker/releases/tag/v4.7.4-rc1.
- [x] Change docker image tag in docker-compose back to 4.7.4 in branch 4.7.4

**Comment by vcerenu** [comment]
LGTM
