### ISSUE TITLE
Support new stage RC 1 for 4.8.0 in wazuh-docker repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-docker#1330]
## Description

This issue attempts to support a new stage RC 1 for 4.8.0 in the wazuh-docker repository.

## Tasks

- [ ] Ensure changelog is updated for 4.8.0 (if applicable).
- [ ] Bump revision for branch 4.8.0 on wazuh-docker repository.
- [ ] Change docker image tag in docker-compose to tag v4.8.0-rc1 in branch 4.8.0
- [ ] Create tag v4.8.0-rc1 from branch 4.8.0 on wazuh-docker repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-docker/releases/tag/v4.8.0-rc1.
- [ ] Change docker image tag in docker-compose back to 4.8.0 in branch 4.8.0

**Comment by Enaraque** [comment]
LGTM
