### ISSUE TITLE
Support new stage RC 2 for 4.8.0 in wazuh-docker repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-docker#1339]
## Description

This issue attempts to support a new stage RC 2 for 4.8.0 in the wazuh-docker repository.

## Tasks

- [x] Ensure changelog is updated for 4.8.0 (if applicable).
- [x] Bump revision for branch 4.8.0 on wazuh-docker repository. https://github.com/wazuh/wazuh-docker/pull/1340
- [x] Change docker image tag in docker-compose to tag v4.8.0-rc2 in branch 4.8.0 https://github.com/wazuh/wazuh-docker/pull/1341
- [x] Create tag v4.8.0-rc2 from branch 4.8.0 on wazuh-docker repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-docker/releases/tag/v4.8.0-rc2.
- [x] Change docker image tag in docker-compose back to 4.8.0 in branch 4.8.0 https://github.com/wazuh/wazuh-docker/pull/1342
