### ISSUE TITLE
Support new stage RC 1 for 4.7.5 in wazuh-docker repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-docker#1348]
## Description

This issue attempts to support a new stage RC 1 for 4.7.5 in the wazuh-docker repository.

## Tasks

- [x] Ensure changelog is updated for 4.7.5 (if applicable).
- [x] Bump revision for branch 4.7.5 on wazuh-docker repository. https://github.com/wazuh/wazuh-docker/pull/1352
- [x] Change docker image tag in docker-compose to tag v4.7.5-rc1 in branch 4.7.5. https://github.com/wazuh/wazuh-docker/pull/1353
- [x] Create tag v4.7.5-rc1 from branch 4.7.5 on wazuh-docker repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-docker/releases/tag/v4.7.5-rc1.
- [x] Change docker image tag in docker-compose back to 4.7.5 in branch 4.7.5. https://github.com/wazuh/wazuh-docker/pull/1354

**Comment by c-bordon** [comment]
LGTM
