### ISSUE TITLE
Fix Base Docker Images vulnerabilities

### ISSUE THREAD

**Issue by teddytpc1** [wazuh/wazuh-docker#1372]
## Description
As part of the [Release 4.8.0 - RC 3 - Artifactory vulnerabilities update (week 22)](https://github.com/wazuh/wazuh-automation/issues/1678) issue, some ALAS vulnerabilities from RC 2 are still being found in RC 3.
The `amazonlinux:2023` image last update was on 16/04/2024.
We must modify the Dockerfiles to update the packages to the latest version.

## Tasks
- [ ] Modify the Dockerfiles of each image to add a command to update all the packages to the latest version.
- [ ] Validate that the ALAS vulnerabilities are fixed.
- [ ] Test the deployment works.

**Comment by teddytpc1** [comment]
We will not fix the vulnerabilities of the base image.
