### ISSUE TITLE
Support new stage Alpha 1 for 4.9.0 in wazuh-docker repository

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-docker#1398]
## Description

This issue attempts to support a new stage Alpha 1 for 4.9.0 in the wazuh-docker repository.

## Tasks

- [x] Ensure changelog is updated for 4.9.0 (if applicable).
- [x] Bump revision for branch 4.9.0 on wazuh-docker repository.
- [x] Change docker image tag in docker-compose to tag v4.9.0-alpha1 in branch 4.9.0
- [x] Create tag v4.9.0-alpha1 from branch 4.9.0 on wazuh-docker repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-docker/releases/tag/v4.9.0-alpha1.
- [x] Change docker image tag in docker-compose back to 4.9.0 in branch 4.9.0

**Comment by CarlosALgit** [comment]
LGTM!
