### ISSUE TITLE
Support new stage RC 2 for 4.8.1 in wazuh-docker repository

### ISSUE THREAD

**Issue by MARCOSD4** [wazuh/wazuh-docker#1417]
## Description

This issue attempts to support a new stage RC 2 for 4.8.1 in the wazuh-docker repository.

## Tasks

- [x] Ensure changelog is updated for 4.8.1 (if applicable).
- [x] Bump revision for branch 4.8.1 on wazuh-docker repository.
- [x] Change docker image tag in docker-compose to tag v4.8.1-rc2 in branch 4.8.1
- [x] Create tag v4.8.1-rc2 from branch 4.8.1 on wazuh-docker repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-docker/releases/tag/v4.8.1-rc2.
- [x] Change docker image tag in docker-compose back to 4.8.1 in branch 4.8.1
