### ISSUE TITLE
Post release tasks for 4.8.1

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-docker#1445]
## Description
This issue attempts to track the steps necessary to complete post-release maintenance tasks for 4.8.1.
The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.8.1-into-4.9.0`.

## Tasks

- [x] Merge branch `4.8.1` into branch `4.9.0`.
- [x] Merge branch `4.9.0` into branch `master`.
- [x] Publish GitHub release as latest.
- [x] Delete all stage pre-releases for 4.8.1 (https://github.com/wazuh/wazuh-docker/releases).
- [x] Delete all stage tags for v4.8.1. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.8.1-rc1, 4.8.1-alpha1, etc.
- [x] Update [Docker hub](https://hub.docker.com/u/wazuh) readme compatibility matrix to include 4.5.3 for manager, dashboard, and indexer.
- [x] Delete all stage [Docker hub images](https://hub.docker.com/u/wazuh) for v4.8.1. **BE CAREFUL NOT TO DELETE DEFINITIVE DOCKER IMAGES**. Example: v4.8.1-rc1, 4.8.1-alpha1, etc.

## Extra tasks

- [x] Revert "Merge branch `4.9.0` into branch `master`".
- [x] Merge branch `4.9.0` into branch `4.10.0`.
- [x] Merge branch `4.10.0` into branch `master`.

**Comment by davidcr01** [comment]
It is necessary to revert the merge of 4.9.0 into master because we need to bump 4.9.0 into 4.10.0, and then, 4.10.0 into master.
