### ISSUE TITLE
Support new stage RC 1 for 4.8.2 in wazuh-docker repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-docker#1485]
## Description

This issue attempts to support a new stage RC 1 for 4.8.2 in the wazuh-docker repository.

## Tasks

- [x] Ensure changelog is updated for 4.8.2 (if applicable). https://github.com/wazuh/wazuh-docker/pull/1487
- [x] Bump revision for branch 4.8.2 on wazuh-docker repository. https://github.com/wazuh/wazuh-docker/pull/1486
- [x] Change docker image tag in docker-compose to tag v4.8.2-rc1 in branch 4.8.2 https://github.com/wazuh/wazuh-docker/pull/1488
- [x] Create tag v4.8.2-rc1 from branch 4.8.2 on wazuh-docker repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-docker/releases/tag/v4.8.2-rc1.
- [x] Change docker image tag in docker-compose back to 4.8.2 in branch 4.8.2 https://github.com/wazuh/wazuh-docker/pull/1489
