### ISSUE TITLE
Post release tasks for 4.9.0

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-docker#1511]
## Description
This issue attempts to track the steps necessary to complete post-release maintenance tasks for 4.9.0.
The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.9.0-into-4.9.1`.

## Tasks

- [x] Merge branch `4.9.0` into branch `4.9.1`. https://github.com/wazuh/wazuh-docker/pull/1512
- [x] Merge branch `4.9.1` into branch `4.10.0`. https://github.com/wazuh/wazuh-docker/pull/1513
- [x] Merge branch `4.10.0` into branch `master`. https://github.com/wazuh/wazuh-docker/issues/1514
- [x] Publish GitHub release as latest.
- [x] Delete all stage pre-releases for 4.9.0 (https://github.com/wazuh/wazuh-docker/releases).
- [x] Delete all stage tags for v4.9.0. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.9.0-rc1, 4.9.0-alpha1, etc.
- [x] Update [Docker hub](https://hub.docker.com/u/wazuh) readme compatibility matrix to include 4.9.0 for manager, dashboard, and indexer.
- [x] Delete all stage [Docker hub images](https://hub.docker.com/u/wazuh) for v4.9.0. **BE CAREFUL NOT TO DELETE DEFINITIVE DOCKER IMAGES**. Example: v4.9.0-rc1, 4.9.0-alpha1, etc.
