### ISSUE TITLE
Post release tasks for 4.9.1

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-docker#1580]
## Description
This issue attempts to track the steps necessary to complete post-release maintenance tasks for 4.9.1.
The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.9.1-into-4.10.0`.

## Tasks

- [x] Merge branch `4.9.1` into branch `4.10.0`. https://github.com/wazuh/wazuh-docker/pull/1581
- [x] Merge branch `4.10.0` into branch `4.10.1`. https://github.com/wazuh/wazuh-docker/pull/1582
- [x] Merge branch `4.10.1` into branch `4.10.2`. https://github.com/wazuh/wazuh-docker/pull/1583
- [x] Merge branch `4.10.2` into branch `master`. https://github.com/wazuh/wazuh-docker/pull/1584
- [x] Publish GitHub release as latest.
- [x] Delete all stage pre-releases for 4.9.1 (https://github.com/wazuh/wazuh-docker/releases).
- [x] Delete all stage tags for v4.9.1. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.9.1-rc1, 4.9.1-alpha1, etc.
- [x] Delete all stage [Docker hub images](https://hub.docker.com/u/wazuh) for v4.9.1. **BE CAREFUL NOT TO DELETE DEFINITIVE DOCKER IMAGES**. Example: v4.9.1-rc1, 4.9.1-alpha1, etc.
