### ISSUE TITLE
Support new stage RC 1 for 4.9.2 in wazuh-docker repository

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh-docker#1596]
## Description

This issue attempts to support a new stage RC 1 for 4.9.2 in the wazuh-docker repository.

## Tasks

- [ ] ~~Delete previous RC 1 release: https://github.com/wazuh/wazuh-docker/releases/tag/v4.9.2-rc1.~~
- [ ] ~~Delete previous v4.9.2-rc1 tag.~~
- [x] Ensure changelog is updated for 4.9.2 (if applicable).
- [x] Bump revision for branch 4.9.2 on wazuh-docker repository. https://github.com/wazuh/wazuh-docker/pull/1597
- [x] Change docker image tag in docker-compose to tag v4.9.2-rc1 in branch 4.9.2 https://github.com/wazuh/wazuh-docker/pull/1598
- [x] Create tag v4.9.2-rc1 from branch 4.9.2 on wazuh-docker repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-docker/releases/tag/v4.9.2-rc1.
- [x] Change docker image tag in docker-compose back to 4.9.2 in branch 4.9.2 https://github.com/wazuh/wazuh-docker/pull/1599
