### ISSUE TITLE
Update GitHub Actions to v4

### ISSUE THREAD

**Issue by teddytpc1** [wazuh/wazuh-docker#1640]
## Description
We need to update the GH Actions `actions/upload-artifact` and `actions/download-artifact` to `v4`.
It was found that `v3` is being used in this workflow:
- https://github.com/wazuh/wazuh-docker/blob/4.10.1/.github/workflows/push.yml

## Tasks
- [ ] Update the version to `v4`
- [ ] Test the workflow
- [ ] Provide evidence of a successful execution

**Comment by vcerenu** [comment]
The version of the required actions has been modified.
A commit has been added to test the execution of the job, which was not entirely successful for other reasons, but the execution of the artifact actions was successful.
https://github.com/wazuh/wazuh-docker/actions/runs/12320188042?pr=1641
