### ISSUE TITLE
Error in multi-node deployment test

### ISSUE THREAD

**Issue by vcerenu** [wazuh/wazuh-docker#1642]
## Description
When running the job to test the deployment on multi-node, the following error is obtained:

![image](https://github.com/user-attachments/assets/e24cb89a-ce46-4aa4-961d-0b375ec72a33)

This error occurs because this step of the job was prepared for Ubuntu 22, and currently, ubuntu-latest is Ubuntu 24, so it is necessary to modify this step.

## Tasks
- [x] Correct the "Free disk space" step, making it suitable for running on Ubuntu 22
- [x] Test the workflow
- [x] Provide evidence of a successful execution

## Related
- https://github.com/wazuh/wazuh-docker/issues/1640

**Comment by vcerenu** [comment]
The step to free up disk space was modified, which had become outdated
The PR test was executed with version v4.9.2 in order to be able to run the complete test and be able to execute the space release correctly
https://github.com/wazuh/wazuh-docker/actions/runs/12321878081?pr=1643

**Comment by vcerenu** [comment]
The new step was moved to a 4.11.0 based branch and the test work fine https://github.com/wazuh/wazuh-docker/actions/runs/12465937700?pr=1663
