### ISSUE TITLE
Update the GitHub runners image from latest to ubuntu-22.04 in Docker workflows

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh-docker#1644]
## Description

Due to the updates that the `latest` images of GitHub runners undergo, we must set a fixed image to avoid failures in our workflows due to updates in the mentioned image.
It is recommended to define the image `ubuntu-22.04`

## Tasks

- [x] Procedure_push_docker_images.yml
- [x] push.yml
- [x] trivy-dashboard.yml
- [x] trivy-indexer.yml
- [x] trivy-manager.yml

## Issue related

https://github.com/wazuh/internal-devel-requests/issues/1890

**Comment by teddytpc1** [comment]
## Test
- https://github.com/wazuh/wazuh-docker/actions/runs/12436731186?pr=1662
