### ISSUE TITLE
Implement explicit copy to allow mounting postfix configuration in Wazuh Manager

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-docker#240]
Hi team,

In order to mount a postfix configuration, adding a explicit copy command similar to the following is required.

https://github.com/wazuh/wazuh-docker/blob/1562808cf61d57caaac46655b983c1667356d7a7/wazuh/config/00-wazuh.sh#L94-L101

This would allow to load postfix configurations in the container and automatically setup said service.

### Task

- [ ] Implement block that check if the folder is not empty and executes the copy

- [ ] Ensure permissions and owners are correct after the copy

- [ ] Test the copy process with/without an empty folder

- [ ] Test the service in the container

Adding this mechanism we would be able to modify the mounting path of postfix and avoid the problem generated in https://github.com/wazuh/wazuh-kubernetes/issues/55

Best regards,

Jose
