### ISSUE TITLE
Find a lightweight and official image to import

### ISSUE THREAD

**Issue by xr09** [wazuh/wazuh-docker#259]
### Description

In order to comply with #252 we need to find an alternative image to use as a base.

The right image is lightweight, functional and most importantly, secure.

### Tasks
- [x] Setup a testing environment with Docker and Snyk
- [x] Test official CentOS image
- [x] Test official Debian image
- [x] Test official Ubuntu image

**Comment by xr09** [comment]
Hey team,

I'm currently doing some security testing with [Snyk](https://snyk.io) (same tool used to report #221 ).

This is the output from our current image  `wazuh/wazuh:latest`:

![Screenshot_20191002_183115](https://user-images.githubusercontent.com/1380243/66063020-d1aeb200-e542-11e9-96bb-b6d5ebf173de.png)

This is one of the high severity vulnerabilities on the image.

![Screenshot_20191002_183422](https://user-images.githubusercontent.com/1380243/66063232-4124a180-e543-11e9-856c-f10508aa292d.png)


Visiting that [link](https://snyk.io/vuln/SNYK-LINUX-GLIBC-438155) we get this:

```
 Improper Data Handling

Affecting glibc package, versions debian:10: <2.28-1 || debian:8: * || debian:9: * 
|| debian:unstable: <2.28-1 || ubuntu:16.04: * || ubuntu:18.04: *
```
So according to `Snyk` only Debian and Ubuntu are affected. 

But RedHat says otherwise.

https://access.redhat.com/security/cve/cve-2009-5155

`Red Hat Enterprise Linux 7 | glibc | Affected`


Let's check another one.

This [report](https://snyk.io/vuln/SNYK-LINUX-GLIBC-438096) again says Debian and Ubuntu are the only vulnerables.

On the RedHat CVE Database says `Under Investigation` but let's test the [exploit](https://sourceware.org/bugzilla/show_bug.cgi?id=24269) on a CentOS 7:

```
[root@e1cad4fb067f /]# echo D | grep -E "$(printf '(\0|)(\\1\\1)*')"
Segmentation fault (core dumped)
```
Again, vulnerable.

After this research I'm not sure about trusting Snyk as the only source of truth, we might spend a lot of man/hours moving away from the current image (or from Ubuntu) and end up in the blind, since Snyk is not reporting correctly. So this is one point to keep in mind.

I'm tempted to say currently their CVE database is much more accurate for Debian/Ubuntu than for CentOS.

Regards.

**Comment by xr09** [comment]
Another example:

https://snyk.io/vuln/SNYK-LINUX-TAR-441202

```
NULL Pointer Dereference

Affecting tar package, versions debian:10: * || debian:8: * || debian:9: * || debian:unstable: *
```

https://access.redhat.com/security/cve/cve-2019-9923

![Screenshot_20191003_145724](https://user-images.githubusercontent.com/1380243/66128434-1c393880-e5ee-11e9-8f0e-f57fad1b218e.png)

**Comment by xr09** [comment]
### Base images size comparison

Currently testing 3 of the officially supported images on Docker Hub, adding our current base image for comparison.

Base Image | MicroBadger Report
------------ | -------------
CentOS 7 | [![](https://images.microbadger.com/badges/image/centos:7.svg)](https://microbadger.com/images/centos:7 "Get your own image badge on microbadger.com")
Debian 10 | [![](https://images.microbadger.com/badges/image/debian.svg)](https://microbadger.com/images/debian "Get your own image badge on microbadger.com")
Ubuntu 18.04 | [![](https://images.microbadger.com/badges/image/ubuntu:bionic.svg)](https://microbadger.com/images/ubuntu:bionic "Get your own image badge on microbadger.com")
phusion/baseimage | [![](https://images.microbadger.com/badges/image/phusion/baseimage.svg)](https://microbadger.com/images/phusion/baseimage "Get your own image badge on microbadger.com")
Wazuh |  <a href="https://microbadger.com/images/wazuh/wazuh:3.10.0_7.3.2" title="Get your own image badge on microbadger.com"><img src="https://images.microbadger.com/badges/image/wazuh/wazuh:3.10.0_7.3.2.svg"></a>

Mind these official images would require some modifications to allow a multi-process container

**Comment by xr09** [comment]
Testing a quick modifications to our current Dockerfile and changing the base images to Buster and Bionic we're getting final images with 228MB and 191MB respectively. 

Still working on the CentOS build.

**Comment by xr09** [comment]
After a few debates we're proposing CentOS 7 as our new base image due to its solid stability and long term support. Any comments would be appreciated.

**Comment by thiscantbeserious** [comment]
Any reason you didn't even gave Alpine a run? Unlike all of the above is by far more lightweight and faster to customize and also built with Docker in mind.

**Comment by xr09** [comment]
Hi @thiscantbeserious, actually we thought about Alpine but this distro doesn't use the standard glibc like the rest (Alpine uses musl libc). This makes it unexplored territory for our core team (and packaging team as well) so we picked a distro with first class support instead.
