### ISSUE TITLE
Rework of Wazuh Docker image

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-docker#273]
Hello,

This issue is for tracking purposes. 

### Actions

- [x] #214 Change internal data persistency circuit breakers.
- [x] #252 Change of base image.
- [x]  #277 Define service integration on Wazuh image
- [x]  #278 Merge active branches with CentOS-S6 rework
- [x]  #296 Test rework of Wazuh Docker image

Regards
