### ISSUE TITLE
Merge active branches with devel-rework

### ISSUE THREAD

**Issue by xr09** [wazuh/wazuh-docker#278]
### Description

With the current image rework a proof of concept was created on the branch `centos-s6-overlay`, this branch was based on `centos-openssl-fips` but it is required a merge in order to introduce latest developments from branches `devel` and `cloud-0.7`. This issue will report progress on this task.

### Tasks

- [x] Merge `centos-s6-overlay` into `devel-rework`
- [x] Merge `3.10-wazuh-refactor` into `devel-rework`
- [x] Merge `devel` and `cloud-0.7` into `devel-rework`
- [x] Define persistent volumes
- [ ] Define dynamic config loading

**Comment by xr09** [comment]
The changes on the `centos-s6-overlay` branch are merged into `devel-rework` already.

Also, versions were bumped to `3.11.1_7.5.1`.

**Comment by xr09** [comment]
Detected some unstability on the wazuh container, it was due to the replacement of some directories with links pointing to the `/var/ossec/data/` volume. This happens on `init.bash` while building the image, then on container startup these folders get populated either from the volume or from its original content, it's a way of assuring persistence for the manager files.

After disabling this behavior the image is running stable again. A new way of achieving data persistence is on the works.

**Comment by xr09** [comment]
### Possible approaches for achieving data persistence on the Wazuh container:

- #### Use the `/var/ossec/data` volume to sync data to and from.

On startup the container will sync the *permanent data* from the volume. (except for the first run)

All *permanent data* will be synced back to the volume periodically on container execution.

One final sync to the volume should be triggered on container shutdown.

**Comment by xr09** [comment]
After some research the former approach was discarded in favor of what the Cloud Team is doing on their branch.

### Persistence Method from Cloud branch

There are 3 file lists containing permanent files, exclusion files and files to delete. This is stored on `permanent_data.env`

On image build the permanent and exclusion file lists are moved to separate folders on `/var/ossec/data_tmp`.


https://github.com/wazuh/wazuh-docker/blob/cloud-0.11/wazuh/config/permanent_data.sh

Later on container execution one of the scripts called by the entrypoint checks for these locations and copies the contents from `/var/ossec/data_tmp` in case these are empty (first time boot with an empty volume, or also when the container boots with no volume at all).

https://github.com/wazuh/wazuh-docker/blob/cloud-0.11/wazuh/config/01-wazuh.sh#L51-L60

All these locations are considered permanent and it will be required to mount volumes on each one of these to correctly ensure data persistence.

```
["/var/ossec/api/configuration"]
["/var/ossec/etc"]
["/var/ossec/logs"]
["/var/ossec/queue"]
["/var/ossec/var/multigroups"]
["/var/ossec/integrations"]
["/var/ossec/active-response/bin"]
["/var/ossec/wodles"]
["/etc/filebeat"]
["/var/lib/filebeat"]
```

**Comment by xr09** [comment]
## Testing
To check for the correct behavior of the image it is required a complete testing routine with several scenarios.

### Testing procedure
Fire up a complete cluster, add agents, check kibana interface, check correct operations.

### Scenarios
- [ ] Test cluster with version `3.10.2_7.5.0` (with required volumes mounted), add agents
- [ ] Test upgrade to `3.11.1_7.5.1` (with same volumes as before), check agents

**Comment by xr09** [comment]
### Scenario: Cluster from scratch (without volumes)

#### Sample docker-compose

```
version: '3.7'

services:
  wazuh:
    build: wazuh
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
.....

```

#### Procedure

- This scenario was launched as a cluster (version `3.11.1_7.5.1`), with no volumes mounted, this scenario is for testing the use case where a user wants to try Wazuh without pretending to preserve any data.

#### Test Results

- [ ] Test passed

The image behavior was as expected, the absence of volumes didn't affect its inner workings at all. Clearly no persistence is possible this way.


### Scenario: Cluster from scratch (with volumes)

#### Sample docker-compose

```
version: '3.7'

services:
  wazuh:
    build: wazuh
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    volumes:
      - ossec_api_configuration:/var/ossec/api/configuration
      - ossec_etc:/var/ossec/etc
      - ossec_logs:/var/ossec/logs
      - ossec_queue:/var/ossec/queue
      - ossec_var_multigroups:/var/ossec/var/multigroups
      - ossec_integrations:/var/ossec/integrations
      - ossec_active_response:/var/ossec/active-response/bin
      - ossec_wodles:/var/ossec/wodles
      - filebeat_etc:/etc/filebeat_etc
      - filebeat_var:/var/lib/filebeat
.....

volumes:
  ossec_api_configuration:
  ossec_etc:
  ossec_logs:
  ossec_queue:
  ossec_var_multigroups:
  ossec_integrations:
  ossec_active_response:
  ossec_wodles:
  filebeat_etc:
  filebeat_var:
```

#### Procedure

- This scenario was launched as a cluster (version `3.11.1_7.5.1`), with all required volumes mounted, this scenario is for testing a production use case where a user wants to install Wazuh and preserve data.

#### Test Results

- [ ] Test passed

Results were positive, the persistence works as expected, first time the volumes are mounted the files are copied from data_tmp to its rightful locations. The following restarts work correctly, data is preserved.
