### ISSUE TITLE
Update kibana plugin config to be compatible with 3.11.0

### ISSUE THREAD

**Issue by xr09** [wazuh/wazuh-docker#286]
### Description 

On the new version of the Wazuh Plugin for Kibana (`3.10.2_7.5.0`) the API configuration has to be written directly to `wazuh.yml`, which was renamed from `config.yml`.

### Tasks
- [x] Remove API setup curl requests from Elasticsearch image
- [x] Write API settings to `wazuh.yml` on Kibana image
- [x] Test a complete cluster

### Related issues
- #285

**Comment by xr09** [comment]
The rename of `config.yml` to `wazuh.yml` brought some internal changes as well, the API settings will no longer be stored in Elastic, the `.wazuh` index got migrated to `wazuh.yml`. 

The new behavior is like this:

- The first time booting `3.11` Wazuh plugin detects if there's an `.wazuh` index and moves it to `wazuh.yml`, this info gets deleted from Elastic.

- On the following restart cycles there will be no `.wazuh` index, so API settings must be setup in `wazuh.yml` on image setup


The following scenarios were tested to assure the Docker image behavior is correct:

- [ ] New deploy
- [ ] Upgrading from `3.10` (rebuild container with 3.11, maintain volumes)
- [ ] Upgrading from `3.10` with Elastic volume (same as previous but preserving Elastic data)

**Comment by jm404** [comment]
Done in https://github.com/wazuh/wazuh-docker/commit/380ba92708c46becc92f3606bdc655373be8b1f7 and https://github.com/wazuh/wazuh-docker/commit/3c7d0f441dbc4a679d7e858ac9a69f0c7529ac6b
