### ISSUE TITLE
Rework of NGINX Docker image

### ISSUE THREAD

**Issue by xr09** [wazuh/wazuh-docker#295]
### Description

This issue is for tracking the rework of the nginx image.

### Tasks
- [x] Review current nginx image
- [x] #301 Fix deprecation warnings
- [x] #302 Fix execution model (PID 1)
- [x] #305 Use htpaswd batch mode
- [x] #307 Enable HTTP v2
- [x] #309 Use official nginx image without rebuilding

**Comment by xr09** [comment]
After a review of the NGINX image 2 issues were found:

- Config file yields deprecation warnings #301
- Nginx is not PID 1 #302

**Comment by xr09** [comment]
Another improvement would be enabling HTTP v2 traffic. This is being tracked on #307

**Comment by xr09** [comment]
After some brainstorming with @manuasir we want to explore the possiblity of not shipping our own nginx image and switch to use the official image as it is.

This idea is being explored at #309
