### ISSUE TITLE
Wazuh Release 3.11.2_7.5.1

### ISSUE THREAD

**Issue by xr09** [wazuh/wazuh-docker#297]
Wazuh version: 3.11.2
Elastic version: 7.5.1

### Tasks

- [x] Adapt to new versions (3.11.2 - 7.5.1)

- [x] Check templates and update them if needed

- [ ] Tests

- [x] Update changelog

- [ ] Tag: v3.11.2_7.5.1

- [x] Update documentation references

- [ ] Draft release
