### ISSUE TITLE
Use official nginx image without rebuilding

### ISSUE THREAD

**Issue by xr09** [wazuh/wazuh-docker#309]
### Description

Currently we're rebuilding the official nginx image, all we're doing is adding a couple of tools and an entrypoint which builds certificates and set things up before starting the web server.

Basically this:

```
RUN apt-get update && apt-get install -y openssl apache2-utils

COPY config/entrypoint.sh /entrypoint.sh
...
ENTRYPOINT /entrypoint.sh
```

This entrypoint will build a self signed certificate and the htpasswd file for basic auth, hence the installed packages `openssl` and `apache2-utils`.

Using the nginx image without rebuilding is possible, by mounting a ready made config directory with these files already.

#### Pros
- more freedom for users to define anything on the config

#### Cons
- build your own htpasswd/certificates

### Tasks
- [x] Create a sample config for nginx to mount
- [x] Rewrite nginx config on `docker-compose.yml` to use external config
- [x] Test execution of the nginx container
- [x] Test cluster execution

**Comment by xr09** [comment]
### Sample config

A sample config will be shipped by default in the `nginx_conf` directory. This will contain a similar config than what our current image is generating on entrypoint execution.


The main README was updated with a link to the secondary README on the ssl directory.

* nginx: Proxies the Kibana container, adding HTTPS (via your [own certificate or self-signed](nginx_conf/ssl/README.md)) and [Basic authentication](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#Basic_authentication_scheme). **It is required to set up SSL certificate before deploying**

#### The contents of the secondary README:

============================

### Enable SSL Traffic

Our Nginx config has SSL enabled by default, but it does require you to provide your certificate first, copy here your certificate files as `kibana-access.pem` and `kibana-access.key`.

The final tree should be like this:

```
nginx_conf/
├── kibana.htpasswd
├── kibana-web.conf
└── ssl
    ├── kibana-access.key
    └── kibana-access.pem
```

#### Using a Self Signed Certificate

In case you want to use a self-signed certificate we provided a script to generate one.

Execute `bash generate-self-signed-cert.sh` on this same directory and the right files will be generated. You must have installed `openssl` locally.

============================


### Usage workflow

The user will clone the repository and provide a valid certificate on the `nginx_conf/ssl` directory or if preferred it is possible to generate one (self-signed) with `openssl`.

An advantage of this workflow is the fact that the certificate will not be re-created on every cluster startup, which is annoying while developing locally, having to accept a new self-signed certificate on the browser every time.

### Execution testing

##### Container 

The nginx container starts up correctly with the folder mount.

![Screenshot_20200205_182853](https://user-images.githubusercontent.com/1380243/73866568-5db04d80-4845-11ea-9593-f5f80c6e0928.png)

##### conf.d structure

```
/etc/nginx/conf.d/
|-- kibana-web.conf
|-- kibana.htpasswd
`-- ssl
    |-- README.md
    |-- generate-self-signed-cert.sh
    |-- kibana-access.key
    `-- kibana-access.pem
```

#### Kibana UI

![Screenshot_20200205_183346](https://user-images.githubusercontent.com/1380243/73866949-0bbbf780-4846-11ea-8773-8166ee0c8136.png)


### Test outcome

After doing all these tests I'm concluding that it is totally possible to omit our re-build of the Nginx image. But we must keep in mind that on one hand it will give more power to the user but also more liability since the creation of required files like certificates and basic auth will be on the user side with this approach.
