### ISSUE TITLE
Wazuh Release 3.12.0_7.6.1

### ISSUE THREAD

**Issue by Zenidd** [wazuh/wazuh-docker#315]
### Wazuh Release
**Wazuh version**: 3.12.0
**Elastic version**: 7.6.1

### Tasks

- [x] Adapt to new versions (3.12.0 - 7.6.1)

- [x] Check templates and update them if needed

- [x] Tests

- [x] Update changelog

- [x] Tag: **v3.12.0_7.6.1**

- [x] Update documentation references

- [ ] Draft release

**Comment by ilhaan** [comment]
Looks like Wazuh 3.12.0 requires `wazuh.yml` to be stored in a new location (`/usr/share/kibana/optimize/wazuh/config/wazuh.yml`) as per [this](https://documentation.wazuh.com/3.12/user-manual/kibana-app/reference/config-file.html). 

Versions prior to this used `/usr/share/kibana/plugins/wazuh/wazuh.yml`. This will need to be updated in the `kibana/config/wazuh_app_config.sh` file of this repo.
