### ISSUE TITLE
Wazuh Agent timestamp is not being properly saved

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-docker#320]
Hi team,

As stated in https://github.com/wazuh/wazuh-kubernetes/issues/77,  the file `/var/ossec/queue/agents-timestamp` is removed when the Wazuh manager container is restarted.

This causes the Agent to show an incorrect registration date.

### Tasks

- [x] Back up the `/var/ossec/queue/agents-timestamp` file

- [x] Ensure it's properly restored between restarts

- [x] Test changes using a deployment with our default `docker-compose.yml`

- [x] Test this approach with version upgrade 3.10 -> 3.12.x_fix

- [x] Test this approach with version upgrade 3.11 -> 3.12.x_fix

- [x] Test this approach with version upgrade 3.12 -> 3.12.x_fix

Best regards,

Jose

**Comment by xr09** [comment]
I've been testing this case and the issue is that our current backup strategy relies on links, the actual **agents-timestamp** file is located on the `/var/ossec/data/queue/agents-timestamp` folder, a link is created at `/var/ossec/queue/agents-timestamp` but on regular operations the manager overwrites the link with an actual file, on reboot the real agents-timestamp is lost and the link to the original empty file will be created on its place.

#### On system startup

![Screenshot_20200401_182616](https://user-images.githubusercontent.com/1380243/78161804-4c02b500-7446-11ea-9da6-b91fe5b48a16.png)

#### After adding one agent

![Screenshot_20200401_182934](https://user-images.githubusercontent.com/1380243/78162164-c0d5ef00-7446-11ea-9df3-10f0248fea5f.png)


#### Rework branch

On the rework branch this does not happen since we're saving the whole queue directory in its own volume.

```
 volumes:
      ....
      - ossec_queue:/var/ossec/queue
      ....
```

**Comment by xr09** [comment]
There's a POC already which saves the whole `queue` directory, but this approach presents a problem when dealing with upgrades, since some of the containing files could change from version to version. 

The list of persistent locations is reduced to these 5 now.

```
DATA_DIRS[((i++))]="api/configuration"
DATA_DIRS[((i++))]="etc"
DATA_DIRS[((i++))]="logs"
DATA_DIRS[((i++))]="queue"
DATA_DIRS[((i++))]="var/multigroups"
```

A feasible solution could be a hybrid bewteen this one and the one used on `devel-rework` which defines a list of **permanent_data_exceptions** giving precenden for the image version of a path instead of the one saved on the volume.

**Comment by xr09** [comment]
A cluster upgrade test was executed from `3.10.2_7.5.0` to `3.11.4_7.6.1`, the cluster started correctly and retained the agents.

When upgrading to `3.12.0_7.6.1` the agents-timestamp file is loaded correctly on the manager and the agents are present but the kibana container is having issues when loading the templates.

**Comment by xr09** [comment]
The manager was not starting correctly since a few of the files on the queue directory were not present on the volume on upgrades from previous versions.



This was solved by copying the missing files from the **queue-template** folder (which is created on build time for cases like this).

```bash
# copy missing files from queue-template (in case this is an upgrade from previous versions)
for filename in /var/ossec/queue-template/*; do
  fname=$(basename $filename)
  echo $fname
  if ! test -e "/var/ossec/data/queue/$fname"; then
    cp -rp "/var/ossec/queue-template/$fname" /var/ossec/data/queue/
  fi
done
```

**Comment by manuasir** [comment]
Done here #323
