### ISSUE TITLE
Rework of Elasticsearch Docker image

### ISSUE THREAD

**Issue by xr09** [wazuh/wazuh-docker#329]
### Description

This issue is for tracking the rework of Elasticsearch image

### Tasks

- [x] Review current image
- [x] Pass variables to base container
- [x] Use official ES image without rebuilding
- [x] Test common scenarios (simple cluster)
- [x] Test on kubernetes

**Comment by xr09** [comment]
### Image review

In order to use the original docker image some of the curl calls on the entrypoint scripts could be moved to the wazuh container and run with a one-time s6-overlay service.

A blocking issue is the setup of the S3 plugin, which is installed on our custom image and configured using the entrypoints scripts.

**Comment by xr09** [comment]
There's a working branch at [feature-pristine-elastic](https://github.com/wazuh/wazuh-docker/pull/333/files).

Now the Elasticsearch section on our docker-compose.yml is looking like this:

```yml
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    hostname: elasticsearch
    restart: always
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elastic_conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
```

The memory_lock setting was enabled to avoid memory swapping.

A basic deploy was tested, more advanced setups (like enabling xpack) will require some work beforehand.

**Comment by xr09** [comment]
#### Summary

Since switching to this new approach of using Elastic's original image and building the service through config mounts and environment variables, users will have absolute freedom for setting up a cluster with the right amount of customization.

#### XPack
In order to use XPack the steps to follow would be similar to [these](https://documentation.wazuh.com/3.12/installation-guide/installing-elastic-stack/protect-installation/xpack.html#xpack-security) and proceeding to mount the certificates as a volume through the docker-compose.

#### Cluster using on ES original image

<details><summary><i>docker-compose</i></summary>
<br>

```yml
version: '3.7'

services:
  wazuh:
    build: wazuh
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    volumes:
      - ossec_api_configuration:/var/ossec/api/configuration
      - ossec_etc:/var/ossec/etc
      - ossec_logs:/var/ossec/logs
      - ossec_queue:/var/ossec/queue
      - ossec_var_multigroups:/var/ossec/var/multigroups
      - ossec_integrations:/var/ossec/integrations
      - ossec_active_response:/var/ossec/active-response/bin
      - ossec_wodles:/var/ossec/wodles
      - filebeat_etc:/etc/filebeat
      - filebeat_var:/var/lib/filebeat

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    hostname: elasticsearch
    restart: always
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elastic_conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  kibana:
    build: kibana
    hostname: kibana
    restart: always
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
      - wazuh:wazuh

  nginx:
    image: nginx:stable
    hostname: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - kibana
    links:
      - kibana:kibana
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d:ro

volumes:
  ossec_api_configuration:
  ossec_etc:
  ossec_logs:
  ossec_queue:
  ossec_var_multigroups:
  ossec_integrations:
  ossec_active_response:
  ossec_wodles:
  filebeat_etc:
  filebeat_var:
```

</details>

`elastic_conf/elasticsearch.yml`

```yml
cluster.name: wazuh-elastic
network.host: 0.0.0.0
```


![Screenshot_2020-04-20 Wazuh - Kibana](https://user-images.githubusercontent.com/1380243/79780499-4eb54380-833c-11ea-808a-0ac5ebe5b31f.png)

![Screenshot_20200420_193047](https://user-images.githubusercontent.com/1380243/79781227-735deb00-833d-11ea-950d-2b35a2e833b9.png)

**Comment by xr09** [comment]
The following is a an example of a deploy with xpack security enabled using the original Elasticsearch Docker image.

docker-compose.yml

```yml
version: '3.7'

services:
  wazuh:
    build: wazuh
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    environment:
      - "USERNAME=elastic"
      - "PASSWORD=SecretPassword"
    volumes:
      - ossec_api_configuration:/var/ossec/api/configuration
      - ossec_etc:/var/ossec/etc
      - ossec_logs:/var/ossec/logs
      - ossec_queue:/var/ossec/queue
      - ossec_var_multigroups:/var/ossec/var/multigroups
      - ossec_integrations:/var/ossec/integrations
      - ossec_active_response:/var/ossec/active-response/bin
      - ossec_agentless:/var/ossec/agentless
      - ossec_wodles:/var/ossec/wodles
      - filebeat_etc:/etc/filebeat
      - filebeat_var:/var/lib/filebeat
      - ./elastic_conf/elastic-certificates.p12:/etc/elastic-certificates.p12

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    hostname: elasticsearch
    restart: always
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ELASTIC_PASSWORD=SecretPassword"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elastic_conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elastic_conf/elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12

  kibana:
    build: kibana
    hostname: kibana
    restart: always
    ports:
      - "5601:5601"
    environment:
      - XPACK_SECURITY_ENABLED=true
      - "ELASTICSEARCH_USERNAME=elastic"
      - "ELASTICSEARCH_PASSWORD=SecretPassword"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
      - wazuh:wazuh

volumes:
  ossec_api_configuration:
  ossec_etc:
  ossec_logs:
  ossec_queue:
  ossec_var_multigroups:
  ossec_integrations:
  ossec_active_response:
  ossec_agentless:
  ossec_wodles:
  filebeat_etc:
  filebeat_var:
```


elasticsearch.yml inside elatic_conf directory:


```yml
cluster.name: wazuh-elastic
network.host: 0.0.0.0
xpack.security.enabled: true
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.keystore.type: PKCS12
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.keystore.path: elastic-certificates.p12
xpack.security.transport.ssl.truststore.path: elastic-certificates.p12
xpack.security.transport.ssl.truststore.type: PKCS12
```
