### ISSUE TITLE
Wazuh Docker release v3.12.3_7.6.2

### ISSUE THREAD

**Issue by xr09** [wazuh/wazuh-docker#339]
### Wazuh Release
**Wazuh version**: 3.12.3
**Elastic version**: 7.6.2

### Tasks

- [ ] Adapt to new versions (3.12.3 - 7.6.2)

- [ ] Check templates and update them if needed

- [ ] Tests

- [ ] Update changelog

- [ ] Tag: **v3.12.3_7.6.2**

- [ ] Update documentation references

- [ ] Draft release
