### ISSUE TITLE
Adapt images to Wazuh v4.0

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-docker#376]
Hello team,

This Wazuh v4.0 is about to be out soon, we're into the adaptation of the Docker images:
To do:

- [x] Update template and package versions
- [x] Test Auto-Enrollment
- [x] Test new API
- [x] Test complete flow with Open Distro
- [x] Implement migration scripts. #385
- [x] Upgrade tests from 3.x to 4.x #381 

Regards
