### ISSUE TITLE
Wazuh Docker release v3.13.2_7.9.1

### ISSUE THREAD

**Issue by xr09** [wazuh/wazuh-docker#382]
### Wazuh Release
**Wazuh version**: 3.13.2
**Elastic version**: 7.9.1

### Tasks

- [x] Adapt to new versions

- [x] Check templates and update them if needed

- [ ] Tests

- [x] Update changelog

- [ ] Tag: **v3.13.2_7.9.1**

- [x] Update documentation references

- [x] Draft release
