### ISSUE TITLE
Allow the creation of custom users for the API

### ISSUE THREAD

**Issue by xr09** [wazuh/wazuh-docker#395]
## Create custom API users before starting Wazuh

With the new RBAC API it is possible to create users with different roles.

It is required to create a new script which will take a JSON file with the custom login details (username, password, role) and will proceed to create it before starting the Wazuh processes.

The script should use the [create_user](https://github.com/wazuh/wazuh/blob/master/framework/wazuh/security.py#L109) function from the framework.

## Tasks:

- [x] Provide env vars to render custom login on JSON file
- [x]  Parse JSON and call the create_user function
- [x] Check user existence on the database
- [x] Test custom logins

**Comment by xr09** [comment]
Current approach:

```python
from sys import path, exit
import json

framework_path = '/var/ossec/framework'
path.append(framework_path)

USER_FILE_PATH = '/var/ossec/api/configuration/admin.json'


try:
    from wazuh.security import create_user, get_users, get_roles, set_user_role, update_user
except Exception as e:
    print("No module 'wazuh' found.")
    exit()

def read_user_file(path=USER_FILE_PATH):
    with open(path) as user_file:
        data = json.load(user_file)
        return data['username'], data['password']

def db_users():
    users_result = get_users()
    return {user['username']:user['id'] for user in users_result.affected_items}

def db_roles():
    roles_result = get_roles()
    return {role['name']:role['id'] for role in roles_result.affected_items}


if __name__ == "__main__":
    username, password = read_user_file()
    if username not in db_users():
        create_user(username=username, password=password)
        users = db_users()
        uid = users[username]
        roles = db_roles()
        rid = roles['administrator']
        set_user_role(user_id=[uid,], role_ids=[rid,])
```



The script is almost complete but currently hitting an IndexError on the `get_username` function:

```python
[root@wazuh-manager ~]# /var/ossec/framework/python/bin/python3 create_user.py 
Traceback (most recent call last):
  File "create_user.py", line 38, in <module>
    set_user_role(user_id=[uid,], role_ids=[rid,])
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.0.0-py3.8.egg/wazuh/rbac/decorators.py", line 417, in wrapper
    result = func(*args, **kwargs) if not skip_execution else None
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.0.0-py3.8.egg/wazuh/security.py", line 635, in set_user_role
    username = get_username(user_id=user_id)
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.0.0-py3.8.egg/wazuh/security.py", line 607, in get_username
    user = am.get_user_id(user_id=int(user_id[0]))
IndexError: list index out of range
```

**Comment by xr09** [comment]
## Workflow to add custom users

- On build time a new script is injected into the image at `/var/ossec/framework/scripts/create_user.py`
- The env variables `API_USERNAME` and `API_PASSWORD` are rendered into a json file at `/var/ossec/api/configuration/admin.json`
```json
{
  "username": "my-custom-login",
  "password": "SomeRandomPa44*-"
}
```
- The password must comply with the strength requirements (uppercase, lowercase, numbers, specials chars and a min of 8 characters)
- The script will read the `admin.json` file and proceed to create the user on the API database.

**Comment by xr09** [comment]
In the case of a weak password the script returns an error but the execution continued, to prevent this error to pass unnoticed the container will show an error message and proceed to shutdown in the case of this script returning an exit code different than `0`.

In this way, it becomes clear that user intervention is required.

![Screenshot_20201023_151413](https://user-images.githubusercontent.com/1380243/97008163-c5790680-1542-11eb-8ca8-d9a700929264.png)
