### ISSUE TITLE
Dockerized wazuh-agent

### ISSUE THREAD

**Issue by Zenidd** [wazuh/wazuh-docker#412]
Hi team,

## Description

Wazuh users regularly ask for a way to run the wazuh-agents in a dockerized environment. This will allow running the agent on any docker-capable platforms without cluttering the host system.

## Tasks

- [ ] Dockerize Wazuh agent.

- [ ] Testing in different environments.

- [ ] Extend documentation and include related example use case.

Greetings,
JP

**Comment by priamai** [comment]
Great idea, would love to test this!

**Comment by christians86** [comment]
Hi, is there any news on this change? I just spent time on another non wazuh docker agent but coulnd't get any way, so I would love to have a docker version for my two qnap nas.

**Comment by alberpilot** [comment]
Hello @christians86 
Sorry for the late response. We have this task in our roadmap. We hope to solve it as soon as possible. 

Thanks.

**Comment by lordraiden** [comment]
@alberpilot any news about this? this could be a game changer from some environments or environments with an OS not supported by the agent.

I have only found this alternative but it looks abandoned right now.
https://github.com/NoEnv/docker-wazuh-agent

**Comment by AurimasNav** [comment]
Interested in this as well as a way to deploy agents on managed kubernetes.
