### ISSUE TITLE
Validate images on Github Actions

### ISSUE THREAD

**Issue by xr09** [wazuh/wazuh-docker#423]
### Description

Curently on our CI pipeline (Github Actions) we are testing that images are built ok and start correctly on `docker-compose up`.

On other repos (e.g. Ansible/Puppet) we have checks like testinfra testing for open ports and installed packages.

This issue will track the implamentation of [Goss](https://github.com/aelsabbahy/goss) on our CI with Github Actions.

### Tasks:

- [x] Research Goss for testing Docker images
- [x] Generate a valid goss.yaml to test the `wazuh-odfe` image
- [x] Implement Goss testing on Github Actions

**Comment by xr09** [comment]
The yaml file is located at `.goss.yaml`, this location is specified on the env var `GOSS_FILE`, then the var `GOSS_SLEEP` allows for the container to wait until all processes are ready to start the testing.

**Comment by xr09** [comment]
Tests are passing:


```yaml
Run dgoss run wazuh/wazuh-odfe:dev-version
INFO: Starting docker container
INFO: Container ID: 39af7b23
INFO: Sleeping for 30
INFO: Container health
INFO: Running Tests
File: /var/ossec/etc/ossec.conf: exists: matches expectation: [true]
File: /var/ossec/etc/ossec.conf: mode: matches expectation: ["0660"]
File: /var/ossec/etc/ossec.conf: owner: matches expectation: ["root"]
File: /var/ossec/etc/ossec.conf: group: matches expectation: ["ossec"]
File: /var/ossec/etc/ossec.conf: filetype: matches expectation: ["file"]
Process: wazuh-db: running: matches expectation: [true]
Process: wazuh-modulesd: running: matches expectation: [true]
Process: ossec-analysisd: running: matches expectation: [true]
Process: ossec-authd: running: matches expectation: [true]
Process: ossec-syscheckd: running: matches expectation: [true]
Process: s6-supervise: running: matches expectation: [true]
File: /etc/filebeat/filebeat.yml: exists: matches expectation: [true]
File: /etc/filebeat/filebeat.yml: mode: matches expectation: ["0644"]
File: /etc/filebeat/filebeat.yml: owner: matches expectation: ["root"]
File: /etc/filebeat/filebeat.yml: group: matches expectation: ["root"]
File: /etc/filebeat/filebeat.yml: filetype: matches expectation: ["file"]
File: /var/ossec/bin/ossec-control: exists: matches expectation: [true]
File: /var/ossec/bin/ossec-control: mode: matches expectation: ["0750"]
File: /var/ossec/bin/ossec-control: owner: matches expectation: ["root"]
File: /var/ossec/bin/ossec-control: group: matches expectation: ["root"]
File: /var/ossec/bin/ossec-control: filetype: matches expectation: ["file"]
Process: filebeat: running: matches expectation: [true]
User: ossecm: exists: matches expectation: [true]
User: ossecm: home: matches expectation: ["/var/ossec"]
User: ossecm: groups: matches expectation: [["ossec"]]
User: ossecm: shell: matches expectation: ["/sbin/nologin"]
User: ossecr: exists: matches expectation: [true]
User: ossecr: home: matches expectation: ["/var/ossec"]
User: ossecr: groups: matches expectation: [["ossec"]]
User: ossecr: shell: matches expectation: ["/sbin/nologin"]
User: ossec: exists: matches expectation: [true]
User: ossec: home: matches expectation: ["/var/ossec"]
User: ossec: groups: matches expectation: [["ossec"]]
User: ossec: shell: matches expectation: ["/sbin/nologin"]
Group: ossec: exists: matches expectation: [true]
Port: tcp:1515: listening: matches expectation: [true]
Port: tcp:1515: ip: matches expectation: [["0.0.0.0"]]
Port: tcp:55000: listening: matches expectation: [true]
Port: tcp:55000: ip: matches expectation: [["0.0.0.0"]]
Port: tcp:1514: listening: matches expectation: [true]
Port: tcp:1514: ip: matches expectation: [["0.0.0.0"]]
Package: filebeat: installed: matches expectation: [true]
Package: filebeat: version: matches expectation: [["7.9.1"]]
Package: wazuh-manager: installed: matches expectation: [true]
Package: wazuh-manager: version: matches expectation: [["4.0.3"]]


Total Duration: 0.066s
Count: 45, Failed: 0, Skipped: 0
INFO: Deleting container
```
