### ISSUE TITLE
[wazuh-docker] Update v4.1.5 with Opendistro 1.13.2

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-docker#476]
# Goal
According to our latest packages release, which only contains new Opendistro packages, we need to update the repository for using those images. After that, Docker Hub must be updated. 

# Tasks
- [x] Modify the repository to bump to 1.13.2 Opendistro version. Take into account the `kibana.yml` [modifications needed](https://github.com/wazuh/wazuh-documentation/blob/4.1/resources/open-distro/kibana/7.x/kibana_all_in_one.yml). 
- [x] Re-do v4.1.5 tag. 
- [x] Make sure that new images are newly built or trigger the build in Docker Hub. Only ODFE is needed. 
- [x] Merge into `stable` branch
- [x] Update `master`, `5.0-dev` and `4.2` with 1.13.2
