### ISSUE TITLE
Docker Release 4.2.1

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-docker#512]
### Tasks

- [x] Merge latest changes 
- [x] Test 4.2.1 branch 
- [x] Create tag 
- [x] Publish images in Dockerhhub 
- [x] Github draft release 
- [x] Github release

**Comment by vcerenu** [comment]
updating tags to 4.2.1

**Comment by vcerenu** [comment]
Version 4.2.1 deployment test was performed, which ended with error. The same test was performed on version 4.2.0 but I have the following error:
```
Caused by: javax.crypto.BadPaddingException: Insufficient buffer remaining for AEAD cipher fragment (2). Needs to be more than tag size (16)
	at sun.security.ssl.SSLCipher$T13GcmReadCipherGenerator$GcmReadCipher.decrypt(SSLCipher.java:1895) ~[?:?]
	at sun.security.ssl.SSLEngineInputRecord.decodeInputRecord(SSLEngineInputRecord.java:240) ~[?:?]
	at sun.security.ssl.SSLEngineInputRecord.decode(SSLEngineInputRecord.java:197) ~[?:?]
	at sun.security.ssl.SSLEngineInputRecord.decode(SSLEngineInputRecord.java:160) ~[?:?]
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:110) ~[?:?]
	at sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:736) ~[?:?]
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:691) ~[?:?]
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:506) ~[?:?]
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:482) ~[?:?]
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:637) ~[?:?]
	at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:282) ~[netty-handler-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1372) ~[netty-handler-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1267) ~[netty-handler-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1314) ~[netty-handler-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501) ~[netty-codec-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440) ~[netty-codec-4.1.49.Final.jar:4.1.49.Final]
```
The creation of the v4.2.1 images could be completed but it was still not possible to perform test deployments before uploading them to Dockerhub

**Comment by teddytpc1** [comment]
I have tested the deployment with 4.2.0 and had an issue with the kibana certificates permissions. To resolve it I had to  change the owner to user 1000 (kibana user) and then the deployment succeeded.
@alberpilot let me know if we have to update the documentation to add a note for this behavior or if we can update the generate-self-signed-cert.sh for Kibana to add a `chown 1000:0` for those certificates.

**Comment by teddytpc1** [comment]
I have tested adding the `chown` command and it worked fine. I asked to @vcerenu to add the change to his 4.2.1 branch.

**Comment by vcerenu** [comment]
Wazuh deployment test was performed in docker with the configuration of the production_cluster.yml file with errors supposedly of permissions on certificates

`nested: ElasticsearchException [failed to initialize SSL TrustManager]; nested: CertificateException [java.io.IOException: Is a directory]; nested: IOException [Is a directory];`

A deployment test is performed with the configuration of the xpack-compose.yml file and the same error was obtained as with the previous deployment.
Elasticsearch version is updated from 7.10.2 to 7.11.2 within the build of the images wazuh / wazuh and wazuh / wazuh-kibana (xpack-from-source.yml)
After continuing with the errors, very low performance of the VM is noted when deploying both yamls by docker-compose. We proceed to increase the VM from 1 to 3 cores and from 8gb to 12gb of ram.
After increasing the resources of the VM, both deploys are carried out, obtaining good results in both cases.

An attempt was made to log in to the dockerhub account to push the images created with the tag 4.2.1 but the account asks for its ID, what we have is the email and we don't have the gmail password for it to ask for a reminder of the ID from account. Also when trying to log in with email and password to dockerhub we get an error that does not allow login because it is an organization account
We proceeded to push the * -odfe images to our own dockerhub account in order to test the deployment in kubernetes together with Gonzalo Acuña.

Inside github we proceeded to save the release data and the new tag. A publication of it was not made so that they can verify it, notify me of corrections if necessary or approve it if it is correct
