### ISSUE TITLE
Review and fix the `README.md` file

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-docker#756]
## Description

User @jeevadotnet has informed us that the password indicated for the Wazuh indexer `admin` user is `admin` according to the `README.md` file of the `wazuh-docker` repository, this is wrong since it should indicate that the password is `SecretPassword`, which is the one used in the `docker-compose.yml` files.

https://github.com/wazuh/wazuh-docker/blob/v4.3.10/single-node/docker-compose.yml#L17

It is necessary to modify this password in the `README.md` file of the following branches: 
- 4.3
- 4.4
- master

In addition, it is necessary to check that the other data indicated (users, passwords, configuration, descriptions, etc.) in the `README.md` file are correct for the three mentioned branches.

## Tasks

- [x] Fix the `INDEXER_PASSWORD` variable value in the `README.md` file of the `4.3`, `4.4`, and `master` branches
- [x] Review and fix if necessary the other values and variables indicated in said file.

## Validation

- [x] The data indicated in the `README.md` file corresponds to the values indicated in the repository configuration files
- [x] The data indicated in the `README.md` file corresponds to the values indicated in the Wazuh documentation
  - https://documentation.wazuh.com/current/deployment-options/docker/index.html
