### ISSUE TITLE
Adapt 4.3 to deploy 4.3.11 with new Opensearch version

### ISSUE THREAD

**Issue by teddytpc1** [wazuh/wazuh-docker#763]
# Changes
Docker deployment for 4.3 is using Opensearch `1.2.0` for indexer and `1.2.4` for dashboard and for `4.3.11` the version changes to `2.4.0`.
That change forces us to update the Docker deployment because some file paths change and `securityadmin.sh` script uses port `9200` instead of `9300`.

# Tasks

### Wazuh indexer
- [x] Bump version to 4.3.11
- [x] Update cert paths for the Wazuh indexer image.
- [x] Update `opensearch.yml` and `security_admin.sh` paths for the Wazuh indexer image.
- [x] Update file paths in `config.sh` and `entrypoint.sh` for Wazuh indexer.
- [x] Update `security_admin.sh` port to 9200.

### Wazuh dashboard
- [x] Update cert paths for the Wazuh dashboard image.

### Wazuh manager
- [x] Modify the Wazuh-manager package install command to install it from a downloaded package.

### Docker Deployment
- [x] Update cert paths for single-node deployment.
- [x] Update cert paths for multi-node deployment.
- [x] Update certs, `opensearch.yml` and `security_admin.sh` paths in the `docker-compose.yml` files.
- [x] Update the images tag to `4.3.11-dev` in the `docker-compose.yml` files.
- [x] Tag the images with the new tag.
- [x] Push 4.3.11 images to DockerHub with `4.3.11-dev` tag.
- [x] Test single-node deployment.
- [x] Test multi-node deployment.

### Deployment
- [x] Update the certs, `opensearch.yml` and `security_admin.sh` paths in the manifests.
- [x] Update the `ES_JAVA_OPTS` variable name to `OPENSEARCH_JAVA_OPTS`.
- [x] Update the tag of the images to `4.3.11-dev` in the manifests.
- [x] Test Kubernetes deployment.

# Deliverables
- [x] Docker image for Wazuh manager with tag `4.3.11-dev` pushed to DockerHub.
- [x] Docker image for Wazuh dashboard with tag `4.3.11-dev` pushed to DockerHub.
- [x] Docker image for Wazuh dashboard with tag `4.3.11-dev` pushed to DockerHub.
- [x] New branch in `wazuh-docker` with name `4.3.11` with the required changes to deploy Wazuh.
- [x] New branch in `wazuh-kubernetes` with name `4.3.11` with the required changes to deploy Wazuh.

**Comment by teddytpc1** [comment]
One branch for each repo was created: `4.3.11`.
All the tasks are completed.
