### ISSUE TITLE
The build images script must use the correct `compose` command

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh-docker#916]
## Description

In https://github.com/wazuh/wazuh/issues/18084, a new error has been fetched while using the `build-image.sh` to build the Wazuh Docker images. 
The error is related to the `compose` version. The latest version of composer (2.x) uses `docker compose` instead of `docker-compose` as command.

The script should check the composer version and use the correct command in order to avoid the following error:
```root@debian:/home/hector/wazuh-docker# build-docker-images/build-images.sh
build-docker-images/build-images.sh: line 17: docker-compose: command not found
root@debian:/home/hector/wazuh-docker#
```

## Tasks

- [x] Modify the `build-image.sh` script to check the composer version.
- [x] Check if the images are correctly built using an older version of composer (<2.x)
- [x] Check if the images are correctly built using a newer version of composer (>2.x)
- [x] Check if the Wazuh Docker installation is performed correctly.

**Comment by davidcr01** [comment]
# Update Report

```
if command -v docker-compose &> /dev/null; then
  docker-compose -f build-docker-images/build-images.yml --env-file .env build --no-cache
else
  docker compose -f build-docker-images/build-images.yml --env-file .env build --no-cache
fi
```

This code first checks if the `docker-compose` command is available. If it is, then the code uses `docker-compose` to build the images. Otherwise, the code uses `docker compose` to build the images.

The `command -v` command checks if the specified command is available in the current environment. The `docker-compose` command is available by default on most Linux distributions.

The `docker compose` command is a newer version of the docker-compose command. It is the recommended way to use Docker Compose. However, the docker-compose command is still supported for backwards compatibility.

## Tests

With this change, the results are the following:

:heavy_check_mark: The Docker images are built when using Docker Compose V1:
```
davidcr01:~/Wazuh/wazuh-docker(4.5.0)$ docker-compose -v
docker-compose version 1.29.2, build unknown
davidcr01:~/Wazuh/wazuh-docker(4.5.0)$ sudo build-docker-images/build-images.sh 
/usr/bin/docker-compose
Building wazuh.manager
Sending build context to Docker daemon  39.94kB
Step 1/27 : FROM ubuntu:focal
 ---> 14be0685b768
Step 2/27 : RUN rm /bin/sh && ln -s /bin/bash /bin/sh
 ---> Running in 6793b9d68ed5
Removing intermediate container 6793b9d68ed5
 ---> 690e309aef2f
```

:heavy_check_mark: The Docker images are built when using Docker Compose V2:

**Comment by davidcr01** [comment]
# Update Report

## Installation with the `docker compose` command

In order to check if the `docker compose` command is compatible with the Wazuh installation process, a single node installation has been performed, using the 4.4.4 version.

1. Building images
```console
davidcr01:~/Wazuh/wazuh-docker(916-compose-command-compatibility)$ sudo bash build-docker-images/build-images.sh 
[+] Building 478.6s (76/77)                                                                             
 => [wazuh.manager internal] load build definition from Dockerfile                                 0.0s
 => => transferring dockerfile: 2.24kB                                                             0.0s
 => [wazuh.indexer internal] load build definition from Dockerfile                                 0.1s
 => => transferring dockerfile: 2.38kB                                                             0.0s
 => [wazuh.manager internal] load .dockerignore                                                    0.1s
 => => transferring context: 2B                                                                    0.0s
 => [wazuh.indexer internal] load .dockerignore                                                    0.1s
 => => transferring context: 2B                                                                    0.0s
 => [wazuh.dashboard internal] load metadata for docker.io/library/ubuntu:focal                  118.7s
 => CACHED [wazuh.dashboard builder  1/17] FROM docker.io/library/ubuntu:focal                     0.0s
 => [wazuh.manager] https://raw.githubusercontent.com/wazuh/wazuh/4.4/extensions/elasticsearch/7.  0.4s
 => [wazuh.manager internal] load build context                                                    0.1s
 => => transferring context: 791B                                                                  0.0s
 => [wazuh.indexer internal] load build context                                                    0.1s
 => => transferring context: 6.22kB                                                                0.0s
 => [wazuh.manager  2/18] RUN rm /bin/sh && ln -s /bin/bash /bin/sh                                0.7s
 => [wazuh.indexer stage-1  2/14] RUN getent group wazuh-indexer || groupadd -r -g 1000 wazuh-ind  0.9s
 => [wazuh.indexer builder 2/9] RUN apt-get update -y && apt-get install curl openssl xz-utils -  29.4s
 => [wazuh.manager  3/18] RUN apt-get update && apt install curl apt-transport-https lsb-release  31.7s
 => [wazuh.indexer stage-1  3/14] RUN useradd --system             --uid 1000             --no-cr  0.6s
 => [wazuh.indexer stage-1  4/14] WORKDIR /usr/share/wazuh-indexer                                 0.1s
 => [wazuh.indexer stage-1  5/14] COPY config/entrypoint.sh /                                      0.1s
 => [wazuh.indexer stage-1  6/14] COPY config/securityadmin.sh /                                   0.1s
 => [wazuh.indexer stage-1  7/14] RUN chmod 700 /entrypoint.sh && chmod 700 /securityadmin.sh      0.4s
 => [wazuh.indexer stage-1  8/14] RUN chown 1000:1000 /*.sh                                        0.5s
 => [wazuh.indexer builder 3/9] COPY config/opensearch.yml /                                       0.1s
 => [wazuh.indexer builder 4/9] COPY config/config.sh .                                            0.1s
 => [wazuh.indexer builder 5/9] COPY config/config.yml /                                           0.1s
 => [wazuh.indexer builder 6/9] COPY config/internal_users.yml /                                   0.1s
 => [wazuh.indexer builder 7/9] COPY config/roles_mapping.yml /                                    0.1s
 => [wazuh.indexer builder 8/9] COPY config/roles.yml /                                            0.1s
 => [wazuh.indexer builder 9/9] RUN bash config.sh                                               320.2s
 => [wazuh.manager  4/18] COPY config/check_repository.sh /                                        0.1s 
 => [wazuh.manager  5/18] RUN chmod 775 /check_repository.sh                                       0.4s 
 => [wazuh.manager  6/18] RUN source /check_repository.sh                                          1.3s 
 => [wazuh.manager  7/18] RUN apt-get update &&     apt-get install wazuh-manager=4.4.4-1        125.8s 
 => [wazuh.manager  8/18] RUN curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/f  15.0s 
 => [wazuh.manager  9/18] RUN curl -L https://github.com/aelsabbahy/goss/releases/latest/download  8.9s 
 => [wazuh.manager 10/18] RUN curl --fail --silent -L https://github.com/just-containers/s6-overl  2.5s 
 => [wazuh.manager 11/18] COPY config/etc/ /etc/                                                   0.2s 
 => [wazuh.manager 12/18] COPY --chown=root:wazuh config/create_user.py /var/ossec/framework/scri  0.1s 
 => [wazuh.manager 13/18] COPY config/filebeat.yml /etc/filebeat/                                  0.1s 
 => [wazuh.manager 14/18] RUN chmod go-w /etc/filebeat/filebeat.yml                                0.4s 
 => [wazuh.manager 15/18] ADD https://raw.githubusercontent.com/wazuh/wazuh/4.4/extensions/elasti  0.1s 
 => [wazuh.manager 16/18] RUN chmod go-w /etc/filebeat/wazuh-template.json                         0.5s 
 => [wazuh.manager 17/18] COPY config/permanent_data.env config/permanent_data.sh /                0.2s 
 => [wazuh.manager 18/18] RUN chmod 755 /permanent_data.sh &&     sync && /permanent_data.sh &&    0.6s 
 => [wazuh.dashboard] exporting to image                                                          10.7s
 => => exporting layers                                                                            5.5s
 => => writing image sha256:9c168a9eddad8989eb6e725804e1ab058207ed6b7765dc181321b01fea8c077f       0.0s
 => => naming to docker.io/wazuh/wazuh-manager:4.4.4                                               0.0s
 => => writing image sha256:06964c49557a7391dc49cc75087f1d17d038178e93f0c991603461137ead8919       0.0s 
 => => naming to docker.io/wazuh/wazuh-indexer:4.4.4                                               0.0s 
 => => writing image sha256:8e4079fd8b673e40af4d5ba54e31a02b967e5b81ebf8d7e9b7401ebca78b8077       0.0s
 => => naming to docker.io/wazuh/wazuh-dashboard:4.4.4                                             0.0s
 => [wazuh.indexer stage-1  9/14] COPY --from=builder --chown=1000:1000 /debian/wazuh-indexer/usr  0.8s
 => [wazuh.indexer stage-1 10/14] COPY --from=builder --chown=0:0 /debian/wazuh-indexer/usr/lib/s  0.1s
 => [wazuh.indexer stage-1 11/14] COPY --from=builder --chown=0:0 /debian/wazuh-indexer/usr/lib/s  0.1s
 => [wazuh.indexer stage-1 12/14] COPY --from=builder --chown=0:0 /debian/wazuh-indexer/usr/lib/t  0.1s
 => [wazuh.indexer stage-1 13/14] RUN chown -R 1000:1000 /usr/share/wazuh-indexer                  3.8s
 => [wazuh.indexer stage-1 14/14] RUN mkdir -p /var/lib/wazuh-indexer && chown 1000:1000 /var/lib  0.5s
 => [wazuh.dashboard internal] load build definition from Dockerfile                               0.1s
 => => transferring dockerfile: 3.43kB                                                             0.0s
 => [wazuh.dashboard internal] load .dockerignore                                                  0.1s
 => => transferring context: 2B                                                                    0.0s
 => [wazuh.dashboard internal] load build context                                                  0.1s
 => => transferring context: 13.44kB                                                               0.0s
 => [wazuh.dashboard builder  2/17] RUN apt-get update && apt install curl libcap2-bin xz-utils   36.0s
 => [wazuh.dashboard stage-1  2/11] RUN apt update && apt install -y libnss3-dev fonts-liberatio  28.8s
 => [wazuh.dashboard stage-1  3/11] RUN getent group wazuh-dashboard || groupadd -r -g 1000 wazuh  0.4s
 => [wazuh.dashboard stage-1  4/11] RUN useradd --system             --uid 1000             --no-  0.5s
 => [wazuh.dashboard stage-1  5/11] COPY config/entrypoint.sh /                                    0.1s
 => [wazuh.dashboard stage-1  6/11] COPY config/wazuh_app_config.sh /                              0.1s
 => [wazuh.dashboard stage-1  7/11] RUN chmod 700 /entrypoint.sh                                   0.4s
 => [wazuh.dashboard stage-1  8/11] RUN chmod 700 /wazuh_app_config.sh                             0.4s
 => [wazuh.dashboard stage-1  9/11] RUN chown 1000:1000 /*.sh                                      0.4s
 => [wazuh.dashboard builder  3/17] RUN mkdir -p /usr/share/wazuh-dashboard                        0.5s
 => [wazuh.dashboard builder  4/17] COPY config/dl_base.sh .                                       0.1s
 => [wazuh.dashboard builder  5/17] RUN bash dl_base.sh                                           42.5s
 => [wazuh.dashboard builder  6/17] COPY config/config.sh .                                        0.1s
 => [wazuh.dashboard builder  7/17] COPY config/config.yml /                                       0.1s
 => [wazuh.dashboard builder  8/17] RUN bash config.sh                                             1.6s
 => [wazuh.dashboard builder  9/17] COPY config/install_wazuh_app.sh /                             0.1s
 => [wazuh.dashboard builder 10/17] RUN chmod 775 /install_wazuh_app.sh                            0.4s
 => [wazuh.dashboard builder 11/17] RUN bash /install_wazuh_app.sh                                22.1s
 => [wazuh.dashboard builder 12/17] COPY config/opensearch_dashboards.yml /usr/share/wazuh-dashbo  0.1s
 => [wazuh.dashboard builder 13/17] COPY config/wazuh.yml /usr/share/wazuh-dashboard/data/wazuh/c  0.1s
 => [wazuh.dashboard builder 14/17] RUN chown 101:101 /usr/share/wazuh-dashboard/config/opensearc  0.3s
 => [wazuh.dashboard builder 15/17] RUN mkdir -p /usr/share/wazuh-dashboard/data/wazuh && chown -  0.5s
 => [wazuh.dashboard builder 16/17] RUN mkdir -p /usr/share/wazuh-dashboard/data/wazuh/config &&   0.4s
 => [wazuh.dashboard builder 17/17] RUN mkdir -p /usr/share/wazuh-dashboard/data/wazuh/logs && ch  0.4s
 => [wazuh.dashboard stage-1 10/11] COPY --from=builder --chown=1000:1000 /usr/share/wazuh-dashbo  4.3s
 => [wazuh.dashboard stage-1 11/11] WORKDIR /usr/share/wazuh-dashboard                             0.
```

2. Generating the certificates
```console
davidcr01:~/Wazuh/wazuh-docker/single-node(916-compose-command-compatibility)$ sudo docker compose -f generate-indexer-certs.yml run --rm generator
[+] Creating 1/0
 ✔ Network single-node_default  Created                                                            0.1s 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 26847  100 26847    0     0   504k      0 --:--:-- --:--:-- --:--:--  504k
Cert tool exists in Packages bucket
04/08/2023 08:43:44 INFO: Admin certificates created.
04/08/2023 08:43:44 INFO: Wazuh indexer certificates created.
04/08/2023 08:43:44 INFO: Wazuh server certificates created.
04/08/2023 08:43:45 INFO: Wazuh dashboard certificates created.
Moving created certificates to destination directory
changing certificate permissions
Setting UID indexer and dashboard
Setting UID for wazuh manager and worker
```
3. Starting the containers with the `docker compose up` command (foreground)
Log:  [output.log](https://github.com/wazuh/wazuh-docker/files/12258915/output.log)

4. Starting the containers with the `docker compose up -d` command (background)
```console
davidcr01:~/Wazuh/wazuh-docker/single-node(916-compose-command-compatibility)$ sudo docker compose up -d | tee output-d.log
[+] Running 3/3
 ✔ Container single-node-wazuh.indexer-1    Started0.5s  
 ✔ Container single-node-wazuh.manager-1    Started0.4s  
 ✔ Container single-node-wazuh.dashboard-1  Started0.8s  
```

5. Shutting down the containers
```console
davidcr01:~/Wazuh/wazuh-docker/single-node(916-compose-command-compatibility)$ sudo docker compose down
[+] Running 4/4
 ✔ Container single-node-wazuh.dashboard-1  Removed                                               10.4s 
 ✔ Container single-node-wazuh.indexer-1    Removed                                                0.5s 
 ✔ Container single-node-wazuh.manager-1    Removed                                                4.1s 
 ✔ Network single-node_default              Removed   
```

To enhance the correct functionality, the access to the Wazuh dashboard has been checked too:
![Captura desde 2023-08-04 10-40-26](https://github.com/wazuh/wazuh-docker/assets/72193239/0f17767f-b890-4340-b375-e5b4d21e1b58)

:heavy_check_mark: With this, it has been checked that the Wazuh Docker installation is compatible with the `docker compose` command. The multinode installation uses the same commands, so it is not necessary to check it explicitly.

**Comment by davidcr01** [comment]
# Update Report

## Conclusions

After discussing with the team, we decided not to modify the images builder script, the related `README.md` files, and the related documentation:
- https://documentation.wazuh.com/current/deployment-options/docker/wazuh-container.html
- https://documentation.wazuh.com/current/deployment-options/docker/container-usage.html
- https://documentation.wazuh.com/current/deployment-options/docker/upgrading-wazuh-docker.html
-[ https://documentation.wazuh.com/current/deployment-options/docker/data-migration.html](https://documentation.wazuh.com/current/deployment-options/docker/data-migration.html)

We have reached this conclusion because of this part of the documentation, where is explained in detail which version of Docker compose install and how to do it. If the steps of the documentation are perfomed correctly, the explained commands will work as expected.
https://documentation.wazuh.com/current/deployment-options/docker/docker-installation.html#docker-compose

The user who wants to use a different Docker compose version should adapt the command to the official documentation.
Besides, no communities were received related to this.

**Comment by teddytpc1** [comment]
I validated with @havidarou and we agreed that no changes are needed.
