### ISSUE TITLE
Support new stage RC 1 for 4.5.0 in wazuh-docker repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-docker#922]
## Description

This issue attempts to support a new stage RC 1 for 4.5.0 in the wazuh-docker repository.

## Tasks

- [x] Ensure changelog is updated for 4.5.0
- [x] Create tag v4.5.0-rc1 from branch 4.5.0 on wazuh-docker repository.
- [x] Create a pre-release: https://github.com/wazuh/wazuh-docker/releases/tag/v4.5.0-rc1

**Comment by teddytpc1** [comment]
Everything is ok.
