### ISSUE TITLE
Support new stage RC 2 for 4.5.1 in wazuh-docker repository

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-docker#944]
## Description

This issue attempts to support a new stage RC 2 for 4.5.1 in the wazuh-docker repository.

## Tasks

- [x] Change revision to `40502`. https://github.com/wazuh/wazuh-docker/pull/945
- [x] Change revision to `40503`. https://github.com/wazuh/wazuh-docker/pull/946
- [x] Ensure changelog is updated for 4.5.1
- [x] Create tag v4.5.1-rc2 from branch 4.5.1 on wazuh-docker repository.
- [x] Create a pre-release: https://github.com/wazuh/wazuh-docker/releases/tag/v4.5.1-rc2

**Comment by davidcr01** [comment]
LGTM.

**Comment by teddytpc1** [comment]
Reviewed by @vcerenu

**Comment by teddytpc1** [comment]
Reviewed by @vcerenu.
