### ISSUE TITLE
Support new stage RC 2 for 4.5.2 in wazuh-docker repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-docker#976]
## Description

This issue attempts to support a new stage RC 2 for 4.5.2 in the wazuh-docker repository.

## Tasks

- [ ] Ensure changelog is updated for 4.5.2 (if applicable).
- [ ] Create tag v4.5.2-rc2 from branch 4.5.2 on wazuh-docker repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-docker/releases/tag/v4.5.2-rc2.
- [ ] Bump revision for branch 4.5.2 on wazuh-docker repository.

**Comment by juliamagan** [comment]
Missing changes in release:

![image](https://github.com/wazuh/wazuh-docker/assets/80041853/158f87dd-9d36-40fa-b37a-ec48b87d83c1)

**Comment by juliamagan** [comment]
LGTM
