### ISSUE TITLE
Remove `goss` from manager image

### ISSUE THREAD

**Issue by teddytpc1** [wazuh/wazuh-docker#979]
### Description 
Some vulnerabilities were found [here](https://github.com/wazuh/external-devel-requests/issues/769). And some of them are related to `goss`. We should analyze if it is safe to remove `goss` from the Wazuh manager Docker image.

### Tasks
- [ ] ~~Run a scan with Anchore over the Wazuh manager image to validate if the vulnerabilities are still present in `4.5.2`.~~
- [x] If the vulnerabilities are still present. Analyze if `goss` can be removed.
- [x] If `goss` can be removed, remove the package from the image and then run the scan with Anchore again to validate if the vulnerabilities go away.
- [ ] Provide the last scan results.

**Comment by vcerenu** [comment]
Anchore is a paid tool, so we cannot perform the vulnerability testing required in the issue.

**Comment by vcerenu** [comment]
Because we do not have `Anchore` to check for vulnerabilities, we check the availability of the `goss` binary inside the container

Before remove installation

<img width="359" alt="image" src="https://github.com/wazuh/wazuh-docker/assets/56500015/ac0155da-1867-4434-93c1-5b78d0770f55">


After remove instalaation

<img width="360" alt="image" src="https://github.com/wazuh/wazuh-docker/assets/56500015/e283f914-e89c-4816-b842-870eed17dc72">
